from rein.core.commits import check_changed_files, check_commit_message
from rein.core.findings import Severity


def _ids(findings):
    return {f.rule_id for f in findings}


def test_good_conventional_message_is_clean():
    assert check_commit_message("feat(api): add token refresh endpoint") == []


def test_empty_message_flagged():
    findings = check_commit_message("   ")
    assert "commit.empty" in _ids(findings)
    assert findings[0].severity == Severity.HIGH


def test_wip_marker_flagged():
    assert "commit.wip-marker" in _ids(check_commit_message("WIP fixing stuff"))


def test_non_conventional_flagged():
    assert "commit.not-conventional" in _ids(check_commit_message("updated some code"))


def test_long_subject_flagged():
    long = "feat: " + "x" * 100
    assert "commit.subject-too-long" in _ids(check_commit_message(long))


def test_missing_blank_line_after_subject():
    msg = "feat: add thing\nbody starts immediately"
    assert "commit.no-blank-line" in _ids(check_commit_message(msg))


def test_coauthored_trailer_flagged_high():
    msg = "feat: add thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>"
    findings = check_commit_message(msg)
    assert "commit.ai-attribution" in _ids(findings)
    flagged = [f for f in findings if f.rule_id == "commit.ai-attribution"]
    assert flagged[0].severity == Severity.HIGH


def test_coauthored_case_insensitive_flagged():
    msg = "fix: stuff\n\nCO-AUTHORED-BY: someone"
    assert "commit.ai-attribution" in _ids(check_commit_message(msg))


def test_generated_with_tool_flagged():
    assert "commit.ai-attribution" in _ids(
        check_commit_message("feat: x\n\nGenerated with Claude")
    )
    assert "commit.ai-attribution" in _ids(
        check_commit_message("feat: x\n\nGenerated by Gemini")
    )


def test_signed_off_by_only_not_flagged():
    msg = "feat: add token refresh\n\nSigned-off-by: Sam <sam@example.com>"
    assert "commit.ai-attribution" not in _ids(check_commit_message(msg))


def test_prose_generated_without_tool_not_flagged():
    msg = "fix: regenerate cache\n\nThe report is generated with care every night."
    assert "commit.ai-attribution" not in _ids(check_commit_message(msg))


def test_sensitive_files_flagged():
    findings = check_changed_files(["src/app.py", ".env", "deploy/id_rsa", "certs/server.pem"])
    assert "commit.sensitive-file" in _ids(findings)
    flagged = {f.path for f in findings}
    assert ".env" in flagged and "deploy/id_rsa" in flagged and "certs/server.pem" in flagged
    assert "src/app.py" not in flagged
